In [2]:

import cufflinks as cf
import chart_studio.plotly as py
import seaborn as sns
import plotly.express as px
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import warnings
warnings.filterwarnings("ignore")
init_notebook_mode(connected=True)
cf.go_offline()

In [3]:
df=pd.read_csv("keep/csv/final_FDD.csv")
df.head()

,Region,Province,RegCode_New,ProvCode_New,Disability,Sex,Status,id,Household Population 5 Years Old and Over with Functional Difficulty,Age: 5-19,Age: 20-34,Age: 35–54,Age: 55-80+
0,BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANA...,BASILAN,PH150000000,PH1900700000,Cognitive Disability,Both Sexes,All,PH150700000,1820,149,144,302,1225
1,BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANA...,BASILAN,PH150000000,PH1900700000,Cognitive Disability,Both Sexes,Mild,PH150700000,1594,117,119,267,1091
2,BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANA...,BASILAN,PH150000000,PH1900700000,Cognitive Disability,Both Sexes,Moderate,PH150700000,174,15,12,28,119
3,BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANA...,BASILAN,PH150000000,PH1900700000,Cognitive Disability,Both Sexes,Severe,PH150700000,52,17,13,7,15
4,BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANA...,BASILAN,PH150000000,PH1900700000,Cognitive Disability,Female,All,PH150700000,1007,66,64,150,727

## line charts

In [21]:
disability = (
    df.loc[(df["Sex"] != "Both Sexes")& (df["Status"] != "All") ]
    .groupby(["Disability", "Region","Sex"], 
             as_index=False)["Household Population 5 Years Old and Over with Functional Difficulty"].sum())
figpx=px.line(disability,x="Sex",y="Household Population 5 Years Old and Over with Functional Difficulty"
            ,color='Disability',markers=True)
#fig.update_traces(textposition="bottomright")
figpx

In [5]:



figgo=go.Figure()
figgo.add_traces(go.Scatter(x=disability["Region"],
                                y=disability["Household Population 5 Years Old and Over with Functional Difficulty"],
                                mode="lines",name="LInes")
                                )
figgo.add_traces(go.Scatter(x=disability["Disability"],
                                y=disability["Household Population 5 Years Old and Over with Functional Difficulty"],
                                mode="lines+markers",name="LInes")
                                )
figgo.add_traces(go.Scatter(x=disability["Sex"],
                                y=disability["Household Population 5 Years Old and Over with Functional Difficulty"],
                                mode="markers",name="LInes")
                                )
figgo.update_layout(
    xaxis=dict(
        showline=True,
        showgrid=True,
        showticklabels=True,
        linecolor="rgb(204,204,204)",
        linewidth=1,
        ticks="outside",
        tickfont=dict(
            family="Arial",
            size=12,
            color="rgb(82,82,82)"
        )
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        showline=True,
        showticklabels=False
    ),
    autosize=True,
    margin=dict(
        autoexpand=False,
        l=20,
        r=20,
        t=1
    ),
    showlegend=True,
    plot_bgcolor="#F0F0F0"
)


figgo.show()

## bar chart

In [6]:
bar_disability = (
    df.loc[(df["Sex"] != "Both Sexes")& (df["Status"] != "All") ]
    .groupby(["Region"], 
             as_index=False)["Household Population 5 Years Old and Over with Functional Difficulty"].sum())

In [7]:
px.bar(disability,x="Disability",y="Household Population 5 Years Old and Over with Functional Difficulty",
       color="Sex",title="disability by sex",
       labels={"Disability":"Disability type",
               "Household Population 5 Years Old and Over with Functional Difficulty":"Disability count"}
               ,barmode="group")





fig=px.bar(bar_disability,x="Region",y="Household Population 5 Years Old and Over with Functional Difficulty",
       color="Region",title="disability by sex",
       labels={"Disability":"Disability type",
               "Household Population 5 Years Old and Over with Functional Difficulty":"Disability count"},
               text="Household Population 5 Years Old and Over with Functional Difficulty"
               )
fig.update_traces(texttemplate="%{text:.2s}",textposition="outside")
fig.update_layout(uniformtext_minsize=10, uniformtext_mode="hide")
fig.update_layout(margin=dict(autoexpand=False,l=50,r=200,t=30),autosize=True,showlegend=True,
                   plot_bgcolor="#F0F0F0")
fig

## Scatter plot

In [8]:
scatter_disability = (
    df.loc[(df["Sex"] != "Both Sexes")& (df["Status"] != "All") ]
    .groupby(["Region"], 
             as_index=False)["Household Population 5 Years Old and Over with Functional Difficulty"].sum())

In [9]:
k=px.scatter(bar_disability,x="Region",y="Household Population 5 Years Old and Over with Functional Difficulty"
           ,color="Region",size="Household Population 5 Years Old and Over with Functional Difficulty",
           hover_data="Household Population 5 Years Old and Over with Functional Difficulty"
           ,hover_name="Region")
k.update_layout(uniformtext_minsize=10, uniformtext_mode="hide")
k.update_layout(margin=dict(autoexpand=False,l=50,r=200,t=30),autosize=True,showlegend=True,
                   plot_bgcolor="#F0F0F0")

In [10]:
#this can be actually be good enough to put in website
prov = (
    df.loc[(df["Sex"] != "Both Sexes")& (df["Status"] != "All") ]
    .groupby(["Province"], 
             as_index=False)["Household Population 5 Years Old and Over with Functional Difficulty"].sum())

figsc=go.Figure()
figsc.add_trace(go.Scatter(x=prov["Province"],
                           y=prov["Household Population 5 Years Old and Over with Functional Difficulty"],
                           mode="markers",  marker_color=prov["Household Population 5 Years Old and Over with Functional Difficulty"],
                           marker=dict(showscale=True ,colorscale='Viridis')))
figsc.update_traces(marker_line_width=1,marker_size=16)
figsc.update_layout(title=dict(text="Scatter plot by region disability"))  
figsc.update_layout(
    margin=dict(autoexpand=False,r=100,l=50,t=50),showlegend=False,autosize=True
                )
figsc

In [11]:

fig=px.bar(prov,x="Province",y="Household Population 5 Years Old and Over with Functional Difficulty",
       color="Province",title="disability by sex",
       labels={"Disability":"Disability type",
               "Household Population 5 Years Old and Over with Functional Difficulty":"Disability count"},
               text="Household Population 5 Years Old and Over with Functional Difficulty"
               )
fig.update_traces(texttemplate="%{text:.2s}",textposition="outside")
fig.update_layout(uniformtext_minsize=10, uniformtext_mode="hide")
fig.update_layout(margin=dict(autoexpand=False,l=50,r=200,t=30),autosize=True,showlegend=True,
                   plot_bgcolor="#F0F0F0")

## piechart

In [12]:

#put in visualization
px.pie(disability,values='Household Population 5 Years Old and Over with Functional Difficulty',names="Disability",
       title="Disability pie",color_discrete_sequence=px.colors.sequential.RdBu)
fig=go.Figure(data=[go.Pie(values=disability["Household Population 5 Years Old and Over with Functional Difficulty"],
                           labels=disability["Disability"],insidetextorientation='radial',hole=0.3)])

fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=20,
                  marker=dict(colors=disability["Disability"], line=dict(color='white',width=1)))
fig

## histogram

In [13]:
from pandas import to_numeric

age=pd.to_numeric(df.iloc[1:,9],errors="coerce").dropna()
px.histogram(x=age,nbins=10,labels={"value":"ages"},title="histogram",marginal="violin")

In [14]:
age.columns.unique()

AttributeError: 'Series' object has no attribute 'columns'

## box plot

In [ ]:
sex = (
    df.loc[(df["Sex"] != "Both Sexes")& (df["Status"] != "All") ]
    .groupby(["Sex"], 
             as_index=False)["Household Population 5 Years Old and Over with Functional Difficulty"].sum())

px.box(disability,x="Sex",y="Household Population 5 Years Old and Over with Functional Difficulty",points="all",color="Sex")

fig=go.Figure()
fig.add_traces(go.Box(x=disability["Sex"],y=disability["Household Population 5 Years Old and Over with Functional Difficulty"],
                      boxpoints="suspectedoutliers",marker=dict(color="red",outliercolor='red'),
    line_color='rgb(8,81,156)',
                      jitter=0.6,marker_color="blue",fillcolor="cyan",whiskerwidth=0.5))
fig.update_layout(title="WHisker plot",yaxis=dict(gridcolor="black",gridwidth=1),paper_bgcolor="gray",plot_bgcolor="gray")

In [ ]:
fig=go.Figure()
fig.add_traces(go.Box(x=disability["Region"],y=disability["Household Population 5 Years Old and Over with Functional Difficulty"],
                      boxpoints="suspectedoutliers",marker=dict(color="red",outliercolor='red'),
    line_color='rgb(8,81,156)',
                      jitter=0.6,marker_color="blue",fillcolor="cyan",whiskerwidth=0.5))
fig.update_layout(title="WHisker plot",yaxis=dict(gridcolor="black",gridwidth=1),paper_bgcolor="gray",plot_bgcolor="gray")

## heatmap

In [ ]:
px.density_heatmap(disability,x="Disability",y="Household Population 5 Years Old and Over with Functional Difficulty")

In [ ]:
bar_disability

,Region,Household Population 5 Years Old and Over with Functional Difficulty
0,BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANA...,352584
1,Cordillera Administrative Region (CAR),249644
2,MIMAROPA Region,539083
3,National Capital Region (NCR),1330494
4,REGION XI (DAVAO REGION),608202
5,REGION XII (SOCCSKSARGEN),808570
6,Region I (Ilocos Region),759896
7,Region II (Cagayan Valley),590029
8,Region III (Central Luzon),1482790
9,Region IV-A (CALABARZON),1649789
10,Region IX (Zamboanga Peninsula),467310
11,Region V (Bicol Region),906942
12,Region VI (Western Visayas),1137917
13,Region VII (Central Visayas),934429
14,Region VIII (Eastern Visayas),705474
15,Region X (Northern Mindanao),532093
16,Region XIII (Caraga),347928